name: chat_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter

dev_dependencies:
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.2

flutter:

  uses-material-design: true
  assets:
    - assets/