// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBECIWKjyr1KJgGBEa_xEENOFcLldvO4Qw',
    appId: '1:839312180754:web:008af8dbb950de3e7c3acb',
    messagingSenderId: '839312180754',
    projectId: 'chatapp-3ffda',
    authDomain: 'chatapp-3ffda.firebaseapp.com',
    storageBucket: 'chatapp-3ffda.appspot.com',
    measurementId: 'G-NL9KCXECB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA68TEI2D0Ogiv9o1R6Wj0MnWwaSRIOtp0',
    appId: '1:839312180754:android:22bbedeb83b7f81e7c3acb',
    messagingSenderId: '839312180754',
    projectId: 'chatapp-3ffda',
    storageBucket: 'chatapp-3ffda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ8K-UlLgDGmT08Ny80m-wSec35MWAQeA',
    appId: '1:839312180754:ios:7516f8e69a17ca4f7c3acb',
    messagingSenderId: '839312180754',
    projectId: 'chatapp-3ffda',
    storageBucket: 'chatapp-3ffda.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
